version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  orchestrator:
    build: ./orchestrator
    ports:
      - "3000:3000"
    environment:
      AUTH_SERVICE_URL: http://auth:3001
      USERS_SERVICE_URL: http://users:3002
      TASKS_SERVICE_URL: http://tasks:3003
    depends_on:
      - auth
      - users
      - tasks

  auth:
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/task_management
      JWT_SECRET: your_jwt_secret_key
    depends_on:
      - postgres

  users:
    build: ./users
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/task_management
    depends_on:
      - postgres

  tasks:
    build: ./tasks
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/task_management
    depends_on:
      - postgres 